Map<String, String> allergenIcons = {
  "almond": "assets/images/peanuts.png",
  "amaranth": "assets/images/vegetable.png",
  "anchovy": "assets/images/fish.png",
  "antipasto": "assets/images/other.png",
  "apple": "assets/images/raw.png",
  "apple pie": "assets/images/sugar.png",
  "apple sauce": "assets/images/other.png",
  "apricot": "assets/images/raw.png",
  "artichoke": "assets/images/vegetable.png",
  "arugula": "assets/images/vegetable.png",
  "asparagus": "assets/images/vegetable.png",
  "aspic": "assets/images/other.png",
  "avocado": "assets/images/vegetable.png",
  "baby back ribs": "assets/images/meat.png",
  "bacon": "assets/images/meat.png",
  "bagel": "assets/images/gluten.png",
  "baguette": "assets/images/gluten.png",
  "baked alaska": "assets/images/sugar.png",
  "baklava": "assets/images/sugar.png",
  "bamboo shoots": "assets/images/vegetable.png",
  "banana": "assets/images/raw.png",
  "barley": "assets/images/gluten.png",
  "basil": "assets/images/vegetable.png",
  "bass": "assets/images/fish.png",
  "bay leaf": "assets/images/vegetable.png",
  "beancurd": "assets/images/vegetable.png",
  "beans": "assets/images/vegetable.png",
  "beef": "assets/images/meat.png",
  "beef carpaccio": "assets/images/meat.png",
  "beef steak": "assets/images/meat.png",
  "beef tartare": "assets/images/meat.png",
  "beet": "assets/images/vegetable.png",
  "beet salad": "assets/images/vegetable.png",
  "beignets": "assets/images/sugar.png",
  "bell pepper": "assets/images/vegetable.png",
  "berry": "assets/images/raw.png",
  "bibimbap": "assets/images/other.png",
  "bilberry": "assets/images/raw.png",
  "birthday cake": "assets/images/sugar.png",
  "biscuits": "assets/images/sugar.png",
  "bitter melon": "assets/images/vegetable.png",
  "black beans": "assets/images/vegetable.png",
  "black currant": "assets/images/raw.png",
  "blackberry": "assets/images/raw.png",
  "blood orange": "assets/images/raw.png",
  "blood sausage": "assets/images/meat.png",
  "blue cheese": "assets/images/milk.png",
  "blueberry": "assets/images/raw.png",
  "blueberry pie": "assets/images/sugar.png",
  "bok choy": "assets/images/vegetable.png",
  "bonbon": "assets/images/sugar.png",
  "boysenberry": "assets/images/raw.png",
  "bread": "assets/images/gluten.png",
  "bread pudding": "assets/images/gluten.png",
  "bread rolls": "assets/images/gluten.png",
  "breadfruit": "assets/images/other.png",
  "breadstick": "assets/images/gluten.png",
  "bream": "assets/images/fish.png",
  "brie": "assets/images/milk.png",
  "brioche": "assets/images/gluten.png",
  "brisket": "assets/images/meat.png",
  "brittle": "assets/images/sugar.png",
  "broad beans": "assets/images/vegetable.png",
  "broccoli": "assets/images/vegetable.png",
  "broccolini": "assets/images/vegetable.png",
  "brown rice": "assets/images/other.png",
  "brownie": "assets/images/sugar.png",
  "brulee": "assets/images/sugar.png",
  "bruschetta": "assets/images/other.png",
  "brussels sprout": "assets/images/vegetable.png",
  "buckwheat": "assets/images/other.png",
  "burrito": "assets/images/other.png",
  "butter": "assets/images/milk.png",
  "cabbage": "assets/images/vegetable.png",
  "caesar salad": "assets/images/other.png",
  "cake": "assets/images/sugar.png",
  "cake pop": "assets/images/sugar.png",
  "calamari": "assets/images/crustacean.png",
  "camembert": "assets/images/milk.png",
  "canape": "assets/images/other.png",
  "candy": "assets/images/sugar.png",
  "candy apple": "assets/images/sugar.png",
  "candy bar": "assets/images/sugar.png",
  "cannoli": "assets/images/sugar.png",
  "cantaloupe": "assets/images/raw.png",
  "caper": "assets/images/other.png",
  "caprese salad": "assets/images/other.png",
  "caramel apple": "assets/images/sugar.png",
  "cardoon": "assets/images/vegetable.png",
  "carp": "assets/images/fish.png",
  "carpaccio": "assets/images/other.png",
  "carrot": "assets/images/vegetable.png",
  "carrot cake": "assets/images/sugar.png",
  "cashew": "assets/images/peanuts.png",
  "cassava": "assets/images/vegetable.png",
  "casserole": "assets/images/other.png",
  "cauliflower": "assets/images/vegetable.png",
  "caviar": "assets/images/other.png",
  "celery": "assets/images/vegetable.png",
  "cereal": "assets/images/other.png",
  "ceviche": "assets/images/other.png",
  "chard": "assets/images/vegetable.png",
  "cheddar": "assets/images/milk.png",
  "cheese": "assets/images/milk.png",
  "cheeseburger": "assets/images/meat.png",
  "cheesecake": "assets/images/sugar.png",
  "cherry": "assets/images/raw.png",
  "cherry tomato": "assets/images/vegetable.png",
  "chestnut": "assets/images/peanuts.png",
  "chicken": "assets/images/meat.png",
  "chicken breast": "assets/images/meat.png",
  "chicken curry": "assets/images/meat.png",
  "chicken leg": "assets/images/meat.png",
  "chicken wings": "assets/images/meat.png",
  "chickpeas": "assets/images/vegetable.png",
  "chili": "assets/images/vegetable.png",
  "chili pepper": "assets/images/vegetable.png",
  "chips": "assets/images/other.png",
  "chives": "assets/images/vegetable.png",
  "chocolate": "assets/images/sugar.png",
  "chorizo": "assets/images/meat.png",
  "chowder": "assets/images/other.png",
  "churros": "assets/images/sugar.png",
  "chutney": "assets/images/other.png",
  "ciabatta": "assets/images/gluten.png",
  "cinnamon roll": "assets/images/sugar.png",
  "citron": "assets/images/raw.png",
  "citrus": "assets/images/raw.png",
  "clam": "assets/images/crustacean.png",
  "clam chowder": "assets/images/other.png",
  "clementine": "assets/images/raw.png",
  "cobbler": "assets/images/sugar.png",
  "cockle": "assets/images/other.png",
  "coconut": "assets/images/raw.png",
  "coleslaw": "assets/images/other.png",
  "collards": "assets/images/vegetable.png",
  "common bean": "assets/images/vegetable.png",
  "compote": "assets/images/other.png",
  "cookie": "assets/images/sugar.png",
  "corn": "assets/images/vegetable.png",
  "corn bread": "assets/images/gluten.png",
  "corn salad": "assets/images/other.png",
  "corned beef": "assets/images/meat.png",
  "cornflakes": "assets/images/other.png",
  "cottage cheese": "assets/images/milk.png",
  "couscous": "assets/images/other.png",
  "crab": "assets/images/crustacean.png",
  "crab cakes": "assets/images/crustacean.png",
  "cracker": "assets/images/gluten.png",
  "cranberry": "assets/images/raw.png",
  "crayfish": "assets/images/crustacean.png",
  "creme brulee": "assets/images/sugar.png",
  "crepe": "assets/images/gluten.png",
  "crescent roll": "assets/images/gluten.png",
  "cress": "assets/images/vegetable.png",
  "crispbread": "assets/images/gluten.png",
  "croissant": "assets/images/gluten.png",
  "croque madame": "assets/images/gluten.png",
  "croquette": "assets/images/gluten.png",
  "crouton": "assets/images/gluten.png",
  "crunch": "assets/images/sugar.png",
  "cucumber": "assets/images/vegetable.png",
  "cupcake": "assets/images/sugar.png",
  "curd": "assets/images/milk.png",
  "currant": "assets/images/raw.png",
  "custard": "assets/images/sugar.png",
  "cuttlefish": "assets/images/crustacean.png",
  "daikon": "assets/images/vegetable.png",
  "dandelion greens": "assets/images/vegetable.png",
  "danish pastry": "assets/images/gluten.png",
  "date": "assets/images/raw.png",
  "deviled eggs": "assets/images/other.png",
  "dough": "assets/images/gluten.png",
  "doughnut": "assets/images/sugar.png",
  "dragonfruit": "assets/images/raw.png",
  "dried apricot": "assets/images/raw.png",
  "dried fruit": "assets/images/raw.png",
  "drumstick": "assets/images/meat.png",
  "duck": "assets/images/meat.png",
  "dumpling": "assets/images/gluten.png",
  "durian": "assets/images/raw.png",
  "eclair": "assets/images/sugar.png",
  "edamame": "assets/images/vegetable.png",
  "eel": "assets/images/fish.png",
  "egg": "assets/images/other.png",
  "egg white": "assets/images/other.png",
  "egg yolk": "assets/images/other.png",
  "eggplant": "assets/images/vegetable.png",
  "elderberry": "assets/images/raw.png",
  "endive": "assets/images/vegetable.png",
  "english muffin": "assets/images/gluten.png",
  "escargots": "assets/images/other.png",
  "falafel": "assets/images/other.png",
  "farfalle": "assets/images/gluten.png",
  "fava beans": "assets/images/vegetable.png",
  "fiddlehead": "assets/images/vegetable.png",
  "fig": "assets/images/raw.png",
  "filet mignon": "assets/images/meat.png",
  "fillet of sole": "assets/images/fish.png",
  "fish": "assets/images/fish.png",
  "fish and chips": "assets/images/fish.png",
  "flan": "assets/images/sugar.png",
  "flatbread": "assets/images/gluten.png",
  "flatfish": "assets/images/fish.png",
  "florence fennel": "assets/images/vegetable.png",
  "focaccia": "assets/images/gluten.png",
  "foie gras": "assets/images/other.png",
  "fondue": "assets/images/milk.png",
  "frankfurters": "assets/images/meat.png",
  "french beans": "assets/images/vegetable.png",
  "french bread": "assets/images/gluten.png",
  "french fries": "assets/images/other.png",
  "french onion soup": "assets/images/other.png",
  "french toast": "assets/images/gluten.png",
  "fried calamari": "assets/images/crustacean.png",
  "fried egg": "assets/images/other.png",
  "fried rice": "assets/images/other.png",
  "frittata": "assets/images/other.png",
  "fritter": "assets/images/sugar.png",
  "frozen yogurt": "assets/images/milk.png",
  "fruit salad": "assets/images/other.png",
  "fruitcake": "assets/images/sugar.png",
  "fudge": "assets/images/sugar.png",
  "fusilli": "assets/images/gluten.png",
  "galette": "assets/images/sugar.png",
  "garlic": "assets/images/vegetable.png",
  "garlic bread": "assets/images/gluten.png",
  "garlic chives": "assets/images/vegetable.png",
  "gazpacho": "assets/images/other.png",
  "gherkin": "assets/images/vegetable.png",
  "ginger": "assets/images/vegetable.png",
  "gnocchi": "assets/images/gluten.png",
  "goats cheese": "assets/images/milk.png",
  "goji berry": "assets/images/raw.png",
  "goose": "assets/images/meat.png",
  "gooseberry": "assets/images/raw.png",
  "gorgonzola": "assets/images/milk.png",
  "gouda": "assets/images/milk.png",
  "goulash": "assets/images/other.png",
  "gourd": "assets/images/vegetable.png",
  "granola": "assets/images/other.png",
  "grape": "assets/images/raw.png",
  "grapefruit": "assets/images/raw.png",
  "greek salad": "assets/images/other.png",
  "green bean": "assets/images/vegetable.png",
  "green onion": "assets/images/vegetable.png",
  "grilled cheese sandwich": "assets/images/gluten.png",
  "grits": "assets/images/other.png",
  "ground beef": "assets/images/meat.png",
  "guacamole": "assets/images/other.png",
  "guava": "assets/images/raw.png",
  "gyoza": "assets/images/other.png",
  "gyro": "assets/images/other.png",
  "habanero pepper": "assets/images/vegetable.png",
  "halibut": "assets/images/fish.png",
  "ham": "assets/images/meat.png",
  "hamburger": "assets/images/meat.png",
  "hash": "assets/images/other.png",
  "hazelnut": "assets/images/peanuts.png",
  "herring": "assets/images/fish.png",
  "honey": "assets/images/other.png",
  "honeydew melon": "assets/images/raw.png",
  "hot dog": "assets/images/meat.png",
  "huckleberry": "assets/images/raw.png",
  "huevos rancheros": "assets/images/other.png",
  "hummus": "assets/images/other.png",
  "ice cream": "assets/images/milk.png",
  "iceberg lettuce": "assets/images/vegetable.png",
  "jackfruit": "assets/images/raw.png",
  "jalapeno": "assets/images/vegetable.png",
  "jelly beans": "assets/images/sugar.png",
  "jerusalem artichoke": "assets/images/vegetable.png",
  "jicama": "assets/images/vegetable.png",
  "jordan almonds": "assets/images/peanuts.png",
  "jujube": "assets/images/raw.png",
  "juniper berry": "assets/images/raw.png",
  "kale": "assets/images/vegetable.png",
  "kebab": "assets/images/other.png",
  "kettle corn": "assets/images/sugar.png",
  "kidney bean": "assets/images/vegetable.png",
  "kingfish": "assets/images/fish.png",
  "kipper": "assets/images/fish.png",
  "kiwi fruit": "assets/images/raw.png",
  "knish": "assets/images/other.png",
  "kohlrabi": "assets/images/vegetable.png",
  "kombu": "assets/images/vegetable.png",
  "kumquat": "assets/images/raw.png",
  "lamb": "assets/images/meat.png",
  "lamb chops": "assets/images/meat.png",
  "lamb's lettuce": "assets/images/vegetable.png",
  "lasagna": "assets/images/gluten.png",
  "lavender": "assets/images/vegetable.png",
  "leek": "assets/images/vegetable.png",
  "lemon": "assets/images/raw.png",
  "lemon peel": "assets/images/raw.png",
  "lentil": "assets/images/vegetable.png",
  "lettuce": "assets/images/vegetable.png",
  "lima bean": "assets/images/vegetable.png",
  "lime": "assets/images/raw.png",
  "lobster": "assets/images/crustacean.png",
  "lobster bisque": "assets/images/crustacean.png",
  "loin": "assets/images/meat.png",
  "lollipop": "assets/images/sugar.png",
  "lotus root": "assets/images/vegetable.png",
  "lox": "assets/images/fish.png",
  "lychee": "assets/images/raw.png",
  "macadamia nut": "assets/images/peanuts.png",
  "macaron": "assets/images/gluten.png",
  "macaroni": "assets/images/gluten.png",
  "macaroon": "assets/images/sugar.png",
  "mackerel": "assets/images/fish.png",
  "mandarin orange": "assets/images/raw.png",
  "mango": "assets/images/raw.png",
  "maple syrup": "assets/images/sugar.png",
  "marjoram": "assets/images/vegetable.png",
  "marshmallow": "assets/images/sugar.png",
  "marzipan": "assets/images/sugar.png",
  "mashed potatoes": "assets/images/vegetable.png",
  "meat": "assets/images/meat.png",
  "meat pie": "assets/images/meat.png",
  "meatball": "assets/images/meat.png",
  "meatloaf": "assets/images/meat.png",
  "melon": "assets/images/raw.png",
  "meringue": "assets/images/sugar.png",
  "millet": "assets/images/other.png",
  "mint": "assets/images/vegetable.png",
  "miso soup": "assets/images/other.png",
  "mochi": "assets/images/sugar.png",
  "mousse": "assets/images/sugar.png",
  "mozzarella": "assets/images/milk.png",
  "muesli": "assets/images/other.png",
  "muffin": "assets/images/gluten.png",
  "mulberry": "assets/images/raw.png",
  "mung bean": "assets/images/vegetable.png",
  "mushroom": "assets/images/vegetable.png",
  "mussel": "assets/images/crustacean.png",
  "mutton": "assets/images/meat.png",
  "nachos": "assets/images/other.png",
  "napa cabbage": "assets/images/vegetable.png",
  "nectarine": "assets/images/raw.png",
  "nigiri": "assets/images/other.png",
  "noodle": "assets/images/gluten.png",
  "nori": "assets/images/vegetable.png",
  "nougat": "assets/images/sugar.png",
  "nut": "assets/images/peanuts.png",
  "oat": "assets/images/other.png",
  "oatmeal": "assets/images/other.png",
  "octopus": "assets/images/crustacean.png",
  "okra": "assets/images/vegetable.png",
  "olive": "assets/images/vegetable.png",
  "omelette": "assets/images/other.png",
  "onion": "assets/images/vegetable.png",
  "onion rings": "assets/images/vegetable.png",
  "orange": "assets/images/raw.png",
  "oyster": "assets/images/crustacean.png",
  "pad thai": "assets/images/other.png",
  "paella": "assets/images/other.png",
  "pancake": "assets/images/gluten.png",
  "pancetta": "assets/images/meat.png",
  "panna cotta": "assets/images/sugar.png",
  "papaya": "assets/images/raw.png",
  "parfait": "assets/images/sugar.png",
  "parmesan": "assets/images/milk.png",
  "parsnip": "assets/images/vegetable.png",
  "passionfruit": "assets/images/raw.png",
  "pasta": "assets/images/gluten.png",
  "pastrami": "assets/images/meat.png",
  "pastry": "assets/images/gluten.png",
  "pate": "assets/images/other.png",
  "pea": "assets/images/vegetable.png",
  "peach": "assets/images/raw.png",
  "peanut": "assets/images/peanuts.png",
  "peapod": "assets/images/vegetable.png",
  "pear": "assets/images/raw.png",
  "pearl onion": "assets/images/vegetable.png",
  "pecan": "assets/images/peanuts.png",
  "penne": "assets/images/gluten.png",
  "pepperoni": "assets/images/meat.png",
  "perch": "assets/images/fish.png",
  "persimmon": "assets/images/raw.png",
  "pho": "assets/images/other.png",
  "pickle": "assets/images/vegetable.png",
  "pie": "assets/images/sugar.png",
  "pike": "assets/images/fish.png",
  "pilaf": "assets/images/other.png",
  "pine nut": "assets/images/peanuts.png",
  "pineapple": "assets/images/raw.png",
  "pistachio": "assets/images/peanuts.png",
  "pita bread": "assets/images/gluten.png",
  "pizza": "assets/images/gluten.png",
  "plum": "assets/images/raw.png",
  "polenta": "assets/images/other.png",
  "pomegranate": "assets/images/raw.png",
  "pomelo": "assets/images/raw.png",
  "popcorn": "assets/images/sugar.png",
  "popovers": "assets/images/gluten.png",
  "poppy seed roll": "assets/images/gluten.png",
  "popsicle": "assets/images/sugar.png",
  "pork": "assets/images/meat.png",
  "pork chop": "assets/images/meat.png",
  "pork pie": "assets/images/meat.png",
  "porridge": "assets/images/other.png",
  "pot roast": "assets/images/meat.png",
  "potato": "assets/images/vegetable.png",
  "potato onion": "assets/images/vegetable.png",
  "poutine": "assets/images/other.png",
  "praline": "assets/images/sugar.png",
  "prawn": "assets/images/crustacean.png",
  "pretzel": "assets/images/gluten.png",
  "prime rib": "assets/images/meat.png",
  "prosciutto": "assets/images/meat.png",
  "prune": "assets/images/raw.png",
  "pudding": "assets/images/sugar.png",
  "pumpkin": "assets/images/vegetable.png",
  "pumpkin seeds": "assets/images/vegetable.png",
  "quiche": "assets/images/other.png",
  "quince": "assets/images/raw.png",
  "quinoa": "assets/images/other.png",
  "radicchio": "assets/images/vegetable.png",
  "radish": "assets/images/vegetable.png",
  "raisin": "assets/images/raw.png",
  "raisin bread": "assets/images/gluten.png",
  "rambutan": "assets/images/raw.png",
  "ramen": "assets/images/gluten.png",
  "raspberry": "assets/images/raw.png",
  "ratatouille": "assets/images/other.png",
  "ravioli": "assets/images/gluten.png",
  "red cabbage": "assets/images/vegetable.png",
  "red velvet cake": "assets/images/sugar.png",
  "rhubarb": "assets/images/vegetable.png",
  "ribbon-cut pasta": "assets/images/gluten.png",
  "rice": "assets/images/other.png",
  "risotto": "assets/images/other.png",
  "roast beef": "assets/images/meat.png",
  "roe": "assets/images/other.png",
  "romaine": "assets/images/vegetable.png",
  "roquefort": "assets/images/milk.png",
  "rosemary": "assets/images/vegetable.png",
  "rutabaga": "assets/images/vegetable.png",
  "sage": "assets/images/vegetable.png",
  "salad": "assets/images/other.png",
  "salami": "assets/images/meat.png",
  "salmon": "assets/images/fish.png",
  "salsa": "assets/images/other.png",
  "samosa": "assets/images/other.png",
  "sandwich": "assets/images/gluten.png",
  "sardine": "assets/images/fish.png",
  "sashimi": "assets/images/other.png",
  "sauerkraut": "assets/images/other.png",
  "sausage": "assets/images/meat.png",
  "sausage roll": "assets/images/meat.png",
  "scallion": "assets/images/vegetable.png",
  "scallop": "assets/images/crustacean.png",
  "scampi": "assets/images/crustacean.png",
  "scone": "assets/images/gluten.png",
  "sea bass": "assets/images/fish.png",
  "seafood": "assets/images/crustacean.png",
  "seaweed salad": "assets/images/vegetable.png",
  "sesame seed": "assets/images/other.png",
  "shallot": "assets/images/vegetable.png",
  "shellfish": "assets/images/crustacean.png",
  "sherbet": "assets/images/sugar.png",
  "shish kebab": "assets/images/meat.png",
  "shortcake": "assets/images/sugar.png",
  "shrimp": "assets/images/crustacean.png",
  "sirloin": "assets/images/meat.png",
  "slaw": "assets/images/other.png",
  "smoked fish": "assets/images/fish.png",
  "smoked salmon": "assets/images/fish.png",
  "snapper": "assets/images/fish.png",
  "snow pea": "assets/images/vegetable.png",
  "soda bread": "assets/images/gluten.png",
  "sorbet": "assets/images/sugar.png",
  "sorghum": "assets/images/other.png",
  "sorrel": "assets/images/vegetable.png",
  "souffle": "assets/images/sugar.png",
  "soup": "assets/images/other.png",
  "spaghetti bolognese": "assets/images/gluten.png",
  "spaghetti carbonara": "assets/images/gluten.png",
  "spare ribs": "assets/images/meat.png",
  "spinach": "assets/images/vegetable.png",
  "split peas": "assets/images/vegetable.png",
  "spring onion": "assets/images/vegetable.png",
  "spring rolls": "assets/images/gluten.png",
  "sprinkles": "assets/images/sugar.png",
  "sprouts": "assets/images/vegetable.png",
  "squash": "assets/images/vegetable.png",
  "squash blossoms": "assets/images/vegetable.png",
  "squid": "assets/images/crustacean.png",
  "star fruit": "assets/images/raw.png",
  "steak": "assets/images/meat.png",
  "stir-fry": "assets/images/other.png",
  "strawberry": "assets/images/raw.png",
  "string bean": "assets/images/vegetable.png",
  "strudel": "assets/images/gluten.png",
  "stuffing": "assets/images/other.png",
  "sturgeon": "assets/images/fish.png",
  "succotash": "assets/images/other.png",
  "summer squash": "assets/images/vegetable.png",
  "sundae": "assets/images/sugar.png",
  "sunflower seeds": "assets/images/other.png",
  "sushi": "assets/images/other.png",
  "sweet potato": "assets/images/vegetable.png",
  "swiss chard": "assets/images/vegetable.png",
  "swiss cheese": "assets/images/milk.png",
  "tabouli": "assets/images/other.png",
  "tacos": "assets/images/gluten.png",
  "tagliatelle": "assets/images/gluten.png",
  "tamale": "assets/images/other.png",
  "tamarind": "assets/images/raw.png",
  "tangerine": "assets/images/raw.png",
  "tart": "assets/images/sugar.png",
  "tartare": "assets/images/other.png",
  "tempura": "assets/images/other.png",
  "tenderloin": "assets/images/meat.png",
  "tiramisu": "assets/images/sugar.png",
  "toast": "assets/images/gluten.png",
  "toffee": "assets/images/sugar.png",
  "tofu": "assets/images/vegetable.png",
  "tomatillo": "assets/images/vegetable.png",
  "tomato": "assets/images/vegetable.png",
  "torte": "assets/images/sugar.png",
  "tortellini": "assets/images/gluten.png",
  "tortilla chips": "assets/images/other.png",
  "trout": "assets/images/fish.png",
  "truffle": "assets/images/vegetable.png",
  "tuna": "assets/images/fish.png",
  "tuna tartare": "assets/images/fish.png",
  "turkey": "assets/images/meat.png",
  "turkey breast": "assets/images/meat.png",
  "turnip": "assets/images/vegetable.png",
  "venison": "assets/images/meat.png",
  "vermicelli": "assets/images/gluten.png",
  "wafer": "assets/images/sugar.png",
  "waffle": "assets/images/gluten.png",
  "walnut": "assets/images/peanuts.png",
  "water chestnut": "assets/images/vegetable.png",
  "watercress": "assets/images/vegetable.png",
  "watermelon": "assets/images/raw.png",
  "whipped cream": "assets/images/milk.png",
  "whoopie pie": "assets/images/sugar.png",
  "winter melon": "assets/images/vegetable.png",
  "yam": "assets/images/vegetable.png",
  "yardlong bean": "assets/images/vegetable.png",
  "yellow summer squash": "assets/images/vegetable.png",
  "yogurt": "assets/images/milk.png",
  "zucchini": "assets/images/vegetable.png"
};
